services:
  - type: web
    name: cover-letter-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
